# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12663d9373aa6e38c987181513af7c7838ae7e6a1c1fab34bda6a729d9fdac5a3ecdbcc71d9e6e67938bc2af76f42f2e270e330d180cdf52207bd8b593fc53c6

test:
  secret_key_base: 736b6d0d98c125930ddb9e2d25c9394989661d60def20a2968fc2e53de3fceb7e4af9c4b5c2c9ef4f02dff66dee1de29a1808e347277814a22993f1a129d2e38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
